apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "homepage.fullname" . }}-config
  labels:
    {{- include "homepage.labels" . | nindent 4 }}
data:
  {{- if .Values.config.services }}
  services.yaml: |
{{ .Values.config.services | indent 4 }}
  {{- end }}
  {{- if .Values.config.settings }}
  settings.yaml: |
{{ .Values.config.settings | indent 4 }}
  {{- end }}
  {{- if .Values.config.widgets }}
  widgets.yaml: |
{{ .Values.config.widgets | indent 4 }}
  {{- end }}
  {{- if .Values.config.bookmarks }}
  bookmarks.yaml: |
{{ .Values.config.bookmarks | indent 4 }}
  {{- end }}